-- Synthetic, run after pol_ai_010_fixture.sql and the step 1 migration, before
-- 20261005120000_pol_ai_010_pazienti.sql. Mirrors the production columns,
-- identity columns and constraints read on 2026-10-05. NEVER run on a real project.
ALTER TABLE public.patients
  ADD COLUMN user_id uuid, ADD COLUMN nome text, ADD COLUMN cognome text, ADD COLUMN data_nascita date,
  ADD COLUMN telefono text, ADD COLUMN email text, ADD COLUMN cf text, ADD COLUMN indirizzo text,
  ADD COLUMN cap text, ADD COLUMN comune text, ADD COLUMN provincia text, ADD COLUMN note text,
  ADD COLUMN annotazioni jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN consenso_whatsapp boolean NOT NULL DEFAULT false, ADD COLUMN consenso_whatsapp_il timestamptz;
-- Production patients.id is GENERATED ALWAYS AS IDENTITY: recreate the fixture key that way.

ALTER TABLE public.patients ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 100);
UPDATE public.patients SET user_id = '10000000-0000-0000-0000-000000000001', nome = 'Mario', cognome = 'Rossi' WHERE id = 1;
UPDATE public.patients SET user_id = '10000000-0000-0000-0000-000000000002', nome = 'Altro', cognome = 'Studio' WHERE id = 2;
ALTER TABLE public.patients ALTER COLUMN user_id SET NOT NULL;

CREATE TABLE public.richiami(
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL, studio_id uuid NOT NULL,
  paziente_id bigint NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  categoria text NOT NULL DEFAULT 'generico', motivo text, data_scadenza date NOT NULL,
  origine text NOT NULL DEFAULT 'manuale', stato text NOT NULL DEFAULT 'da_fare', chiave_bot text,
  created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.todos(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, testo text NOT NULL, fatto boolean DEFAULT false,
  data date, created_at timestamptz DEFAULT now(), studio_id uuid,
  paziente_id bigint REFERENCES public.patients(id) ON DELETE SET NULL,
  origine text NOT NULL DEFAULT 'manuale', categoria text,
  CONSTRAINT todos_origine_check CHECK (origine = ANY (ARRAY['manuale'::text, 'controllo_dati'::text])));
ALTER TABLE public.impegni_personali
  ADD COLUMN user_id uuid, ADD COLUMN titolo text, ADD COLUMN tipo text NOT NULL DEFAULT 'personale', ADD COLUMN note text,
  ADD CONSTRAINT date_range_valida CHECK (data_fine >= data_inizio),
  ADD CONSTRAINT impegni_personali_tipo_check CHECK (tipo = ANY (ARRAY['personale', 'ferie', 'chiamata', 'altro']));
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['richiami','todos'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format('CREATE POLICY tenant ON public.%I TO authenticated USING (studio_id = (auth.jwt()->''app_metadata''->>''studio_id'')::uuid) WITH CHECK (studio_id = (auth.jwt()->''app_metadata''->>''studio_id'')::uuid)', t);
 END LOOP;
END $$;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.richiami, public.todos TO authenticated;
-- The base fixture inserts impegni with explicit ids: align the identity sequence (production is in sync).
SELECT setval(pg_get_serial_sequence('public.impegni_personali', 'id'), coalesce((SELECT max(id) FROM public.impegni_personali), 0) + 1, false);
