-- Synthetic standalone fixture; NEVER run against an existing project.
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT current_setting('test.user',true)::uuid $$;
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_build_object('app_metadata',jsonb_build_object('studio_id',current_setting('test.studio',true))) $$;
GRANT USAGE ON SCHEMA auth TO authenticated, anon;
CREATE TABLE public.studios(id uuid PRIMARY KEY);
CREATE TABLE public.studio_users(studio_id uuid, user_id uuid, stato text);
CREATE TABLE public.patients(id bigint PRIMARY KEY, studio_id uuid);
CREATE TABLE public.operatori(id bigint PRIMARY KEY, studio_id uuid, nome text, attivo boolean);
-- Mirrors production: appointments.id is GENERATED ALWAYS AS IDENTITY (an explicit id is rejected).
CREATE TABLE public.appointments(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, studio_id uuid, user_id uuid, paziente_id bigint,
 data date, ora text, durata integer DEFAULT 30, tipo text, stato text DEFAULT 'confermato', note text, operatore_id bigint);
CREATE TABLE public.impegni_personali(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, studio_id uuid, data_inizio date, data_fine date,
 tutto_il_giorno boolean, ora_inizio time, ora_fine time);
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['studio_users','patients','operatori','appointments','impegni_personali'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('CREATE POLICY tenant ON public.%I TO authenticated USING (studio_id = (auth.jwt()->''app_metadata''->>''studio_id'')::uuid) WITH CHECK (studio_id = (auth.jwt()->''app_metadata''->>''studio_id'')::uuid)',t);
 END LOOP;
END $$;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
INSERT INTO studios VALUES ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
INSERT INTO auth.users VALUES ('10000000-0000-0000-0000-000000000001'),('10000000-0000-0000-0000-000000000002');
INSERT INTO studio_users SELECT id, ('10000000-0000-0000-0000-00000000000'||right(id::text,1))::uuid,'attivo' FROM studios;
INSERT INTO patients VALUES (1,'00000000-0000-0000-0000-000000000001'),(2,'00000000-0000-0000-0000-000000000002');
INSERT INTO operatori VALUES (1,'00000000-0000-0000-0000-000000000001','Operatore A',true),(2,'00000000-0000-0000-0000-000000000001','Operatore B',true);
