-- POL-002A disposable local fixture baseline.
-- TEST ONLY: this is not a production schema reconstruction or migration.
-- It contains only the verified object contracts needed by the POL-002A tests.
-- All identifiers and rows below are synthetic.

\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE public.studio_users (
  user_id uuid NOT NULL,
  studio_id uuid NOT NULL,
  ruolo text NOT NULL,
  stato text NOT NULL,
  PRIMARY KEY (user_id, studio_id)
);

CREATE TABLE public.patients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  studio_id uuid NOT NULL,
  nome text NOT NULL
);

ALTER TABLE public.studio_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

-- Reproduce only the verified pre-POL-002A fail-open contract so the migration
-- has the same security boundary to replace.
CREATE OR REPLACE FUNCTION public.is_studio_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
  SELECT coalesce(
    (
      SELECT su.ruolo = 'admin' AND su.stato = 'attivo'
      FROM public.studio_users AS su
      WHERE su.user_id = auth.uid()
        AND su.studio_id = (auth.jwt() -> 'app_metadata' ->> 'studio_id')::uuid
      LIMIT 1
    ),
    true
  );
$function$;

CREATE OR REPLACE FUNCTION public.gdpr_esporta_paziente(
  p_paziente_id bigint,
  p_studio_id uuid,
  p_eseguita_da uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
DECLARE
  v_patient public.patients%ROWTYPE;
BEGIN
  SELECT * INTO v_patient
  FROM public.patients
  WHERE id = p_paziente_id AND studio_id = p_studio_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'patient_id', v_patient.id,
    'executed_by', p_eseguita_da
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.gdpr_cancella_paziente(
  p_paziente_id bigint,
  p_studio_id uuid,
  p_eseguita_da uuid,
  p_cancella_anche_fatture boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
DECLARE
  v_deleted bigint;
BEGIN
  DELETE FROM public.patients
  WHERE id = p_paziente_id AND studio_id = p_studio_id
  RETURNING id INTO v_deleted;

  RETURN jsonb_build_object(
    'ok', v_deleted IS NOT NULL,
    'executed_by', p_eseguita_da,
    'delete_invoices', p_cancella_anche_fatture
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_kpi_periodo(
  p_studio_id uuid,
  p_data_inizio date,
  p_data_fine date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
BEGIN
  IF p_studio_id IS DISTINCT FROM
     (auth.jwt() -> 'app_metadata' ->> 'studio_id')::uuid THEN
    RAISE EXCEPTION 'Accesso negato' USING ERRCODE = '42501';
  END IF;
  RETURN jsonb_build_object('ok', true, 'from', p_data_inizio, 'to', p_data_fine);
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_costo_orario(p_studio_id uuid)
RETURNS numeric
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
BEGIN
  IF p_studio_id IS DISTINCT FROM
     (auth.jwt() -> 'app_metadata' ->> 'studio_id')::uuid THEN
    RAISE EXCEPTION 'Accesso negato' USING ERRCODE = '42501';
  END IF;
  RETURN 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN NEW;
END;
$function$;

-- Minimal ACL-only stand-ins for functions classified by verified metadata.
CREATE OR REPLACE FUNCTION public.admin_delete_studio() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.admin_get_ai_usage() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.admin_list_studios() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.admin_remove_studio_user() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.admin_update_studio() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.admin_update_studio_user_role() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.set_agente_azione() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.set_multi_operatore() RETURNS void LANGUAGE sql AS 'SELECT';

CREATE OR REPLACE FUNCTION public.info_link_firma_consenso() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.info_link_storia_clinica() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.info_studio_pubblico() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.prenota_slot_pubblico() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.registra_firma_consenso() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.slot_occupati_pubblico() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.tipi_prenotabili_online() RETURNS void LANGUAGE sql AS 'SELECT';
CREATE OR REPLACE FUNCTION public.register_studio() RETURNS void LANGUAGE sql AS 'SELECT';

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.studio_users, public.patients TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

INSERT INTO public.studio_users (user_id, studio_id, ruolo, stato) VALUES
  ('10000000-0000-0000-0000-000000000001', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'admin', 'attivo'),
  ('10000000-0000-0000-0000-000000000002', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'utente', 'attivo'),
  ('10000000-0000-0000-0000-000000000003', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'admin', 'inattivo'),
  ('20000000-0000-0000-0000-000000000001', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'admin', 'attivo');

INSERT INTO public.patients (id, studio_id, nome) VALUES
  (1001, 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Paziente Sintetico A'),
  (2001, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Paziente Sintetico B');

COMMIT;
