import { normalizeItalianOperational } from './poliedron-language.js';
import { parseDay, parseTime, parseAppointmentChange, isOtherDomain, hasUnreadTime, DAY_WORDS } from './poliedron-agenda.js';
import { parseCoreAction } from './poliedron-actions.js';
export const POLIEDRON_CORE_VERSION='1.0';
const clean=(v='')=>String(v).trim().replace(/\s+/g,' '), lower=(v='')=>clean(v).toLocaleLowerCase('it-IT');
export function parseItalianDay(text=''){return parseDay(lower(text))}
export function parseItalianTime(text=''){return parseTime(lower(text))}
// An agenda write whose time could not be read asks again: never keep the old time or guess one.
const TIME_SENSITIVE=new Set(['APPOINTMENT_CREATE','APPOINTMENT_MOVE','APPOINTMENT_DELETE','APPOINTMENT_UPDATE','AGENDA_BLOCK','AGENDA_AVAILABILITY']);
export function understandPoliedron(text=''){const r=understandPoliedronRaw(text);if(TIME_SENSITIVE.has(r.intent)&&hasUnreadTime(normalizeItalianOperational(clean(text))))return{...r,missing:[...new Set([...(r.missing||[]),'time_unclear'])]};return r}
function understandPoliedronRaw(text=''){const raw=clean(text),q=normalizeItalianOperational(raw);if(!q)return{intent:'UNKNOWN',confidence:0,entities:{},missing:[]};const day=parseItalianDay(q),time=parseItalianTime(q),entities={...(day||{}),...(time||{})};
const action=parseCoreAction(raw);if(action)return action;
const change=parseAppointmentChange(q);if(change)return change;
// "Trova un posto per Mario Rossi giovedì (per igiene)": a booking still missing the time; the answer lists the free slots.
const slot=q.match(new RegExp(`^(?:trova|trovami|cerca|cercami|dammi|proponi|proponimi)\\s+(?:un\\s+)?(?:posto|spazio|buco|orario|appuntamento)(?:\\s+liber[oi])?\\s+(?:per|a)\\s+([a-zà-ÿ' -]{3,60}?)(?=\\s+(?:${DAY_WORDS}|il\\s+\\d|\\d|per)(?![a-zà-ÿ])|$)`));if(slot){const tm=q.match(/\b(?:per|tipo)\s+(igiene|controllo|visita|devitalizzazione|estrazione|implantologia|ortodonzia)\b/);return{intent:'APPOINTMENT_CREATE',confidence:.94,entities:{...entities,patient_query:slot[1].trim(),tipo:tm?tm[1]:'Visita'},missing:[...(!day?['day']:[]),...(!time?['time']:[])]};}
if((/\bappuntament\w*\b|\bagenda\b/.test(q))&&!/\b(?:crea|fissa|sposta|cancella|elimina)\b/.test(q))return{intent:'AGENDA_READ',confidence:.99,entities,missing:day?[]:['day']};
if(/\b(?:liber[oia]|disponibilit[aà]|spazio|posto|posti|buchi)\b/.test(q)&&(day||/\b(?:ho|agenda|alle|ore)\b/.test(q)))return{intent:'AGENDA_AVAILABILITY',confidence:.97,entities,missing:!day?['day']:[]};
if(/\b(?:fissa|prenota|inserisci|aggiungi)\b/.test(q)&&!/\bappuntament\w*\b/.test(q)&&day&&!isOtherDomain(q)){const m=q.match(new RegExp(`\\b(?:fissa|prenota|inserisci|aggiungi)\\s+([a-zà-ÿ' -]{3,70}?)(?=\\s+(?:il\\s+\\d|\\d|${DAY_WORDS}|alle|ore|per)(?![a-zà-ÿ]))`));const tm=q.match(/\b(?:per|tipo)\s+(igiene|controllo|visita|devitalizzazione|estrazione|implantologia|ortodonzia)\b/);const e={...entities,...(m?{patient_query:m[1].trim().replace(/^in agenda\s+/,'')}:{}),tipo:tm?tm[1]:'Visita'};return{intent:'APPOINTMENT_CREATE',confidence:.94,entities:e,missing:[...(!m?['patient']:[]),...(!day?['day']:[]),...(!time?['time']:[])]};}
const patient=q.match(/^(?:cerca|trova|apri|scheda)\s+(?:il\s+)?(?:paziente\s+)?(.{2,80})$/);if(patient)return{intent:'PATIENT_SEARCH',confidence:.98,entities:{query:patient[1].trim()},missing:[]};
if(/\b(?:richiam\w*|controlli? periodici?)\b/.test(q))return{intent:'RECALLS_READ',confidence:.98,entities:{entro_giorni:30},missing:[]};
if(/\b(?:fatturat\w*|incassat\w*|margine\w*|ebitda|break[ -]?even|kpi|situazione economica)\b/.test(q))return{intent:'KPI_READ',confidence:.97,entities:{},missing:[]};
if(/\b(?:crea|fissa|aggiungi|inserisci)\b/.test(q)&&/\bappuntament\w*\b/.test(q)){const after=q.replace(/^.*?\bappuntament\w*\b\s*/i,'');const pm=after.match(new RegExp(`^(?:(?:per|a|al|alla|di|del|della|paziente)\\s+)?(?!(?:${DAY_WORDS}|il|alle|ore|per|tipo|di|igiene|controllo|visita|devitalizzazione|estrazione|implantologia|ortodonzia)(?![a-zà-ÿ]))([a-zà-ÿ' -]{3,80}?)(?=\\s+(?:il\\s+\\d|\\d|${DAY_WORDS}|alle|ore|per\\s+(?:igiene|controllo|visita|devitalizzazione|estrazione|implantologia|ortodonzia))(?![a-zà-ÿ])|$)`,'i'));const tm=q.match(/(?:tipo|per|di)\s+(igiene|controllo|visita|devitalizzazione|estrazione|implantologia|ortodonzia)\b/i);const e={...entities,...(pm?{patient_query:pm[1].trim()}:{}),tipo:tm?tm[1].trim():'Visita'};return{intent:'APPOINTMENT_CREATE',confidence:.94,entities:e,missing:[...(!pm?['patient']:[]),...(!day?['day']:[]),...(!time?['time']:[])]}};
return{intent:'UNKNOWN',confidence:0,entities:{},missing:[]}}
export function coreDecision(p){if(!p||p.intent==='UNKNOWN')return{action:'ESCALATE_LLM',reason:'unknown_intent'};if(p.missing?.length)return{action:'CLARIFY',missing:p.missing};if(['AGENDA_READ','PATIENT_SEARCH','RECALLS_READ','KPI_READ'].includes(p.intent))return{action:'EXECUTE_READ'};if(['APPOINTMENT_CREATE','APPOINTMENT_MOVE','APPOINTMENT_DELETE'].includes(p.intent))return{action:'PREPARE_WRITE_CONFIRMATION'};return{action:'ESCALATE_LLM',reason:'unsupported_intent'}}
