-- POL-WA-003a: the WhatsApp assistant becomes a real assistant.
-- Product Owner decisions (2026-10-02): appointments are PROPOSED by the
-- assistant and CONFIRMED by staff; the assistant always answers but pauses
-- on a conversation as soon as staff writes from the phone (Coexistence);
-- it gives studio info, the patient's own balance and recalls, and hands
-- over to staff when needed.
--
-- Additive only:
--   * richieste_prenotazione gains the columns a WhatsApp request needs, so
--     WhatsApp requests land in the SAME "Richieste di prenotazione" list the
--     Agenda already shows for the public booking page (no parallel flow).
--   * whatsapp_messages.origine tells patient / assistant / staff apart.
--   * whatsapp_conversazioni: per-number state (AI pause, staff hand-over).
--   * whatsapp_saldo_paziente_v1: service-role-only read of the patient's open
--     balances, the same query and acceptance gate as get_saldi_aperti_studio
--     (POL-FIN-006/007), restricted to one patient. No new financial formula.
--
-- Rollback (drops only what this file adds):
--   DROP FUNCTION IF EXISTS public.whatsapp_saldo_paziente_v1(uuid, bigint);
--   DROP TABLE IF EXISTS public.whatsapp_conversazioni;
--   ALTER TABLE public.whatsapp_messages DROP COLUMN IF EXISTS origine;
--   ALTER TABLE public.richieste_prenotazione DROP COLUMN IF EXISTS origine,
--     DROP COLUMN IF EXISTS paziente_id, DROP COLUMN IF EXISTS tipo_richiesta,
--     DROP COLUMN IF EXISTS appuntamento_id, DROP COLUMN IF EXISTS ora_preferita;
BEGIN;

DO $preflight$
BEGIN
  IF to_regclass('public.whatsapp_messages') IS NULL
     OR to_regclass('public.patients') IS NULL
     OR to_regclass('public.appointments') IS NULL
     OR to_regclass('public.plans') IS NULL THEN
    RAISE EXCEPTION 'POL-WA-003a preflight: whatsapp_messages, patients, appointments and plans are required';
  END IF;
  IF to_regclass('private.incassi_plan_saldo_v1') IS NULL
     OR to_regclass('private.financial_live_data_quality_v1') IS NULL THEN
    RAISE EXCEPTION 'POL-WA-003a preflight: POL-FIN saldo views are required';
  END IF;
END
$preflight$;

-- ── richieste_prenotazione baseline ──────────────────────────────────────
-- The table exists in production (public booking page) but was never in a
-- repository migration. Definition extracted read-only on 2026-10-02; this is
-- a no-op where the table already exists.
CREATE TABLE IF NOT EXISTS public.richieste_prenotazione (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  studio_id uuid NOT NULL REFERENCES public.studios(id),
  nome text NOT NULL,
  cognome text NOT NULL,
  telefono text NOT NULL,
  email text,
  date_preferite date[] NOT NULL,
  motivo text,
  note text,
  stato text NOT NULL DEFAULT 'nuova' CONSTRAINT richieste_prenotazione_stato_check CHECK (stato IN ('nuova', 'gestita', 'rifiutata')),
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.richieste_prenotazione ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'richieste_prenotazione' AND policyname = 'richieste_prenotazione_studio') THEN
    CREATE POLICY richieste_prenotazione_studio ON public.richieste_prenotazione FOR SELECT
      USING (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'richieste_prenotazione' AND policyname = 'richieste_prenotazione_studio_update') THEN
    CREATE POLICY richieste_prenotazione_studio_update ON public.richieste_prenotazione FOR UPDATE
      USING (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid)
      WITH CHECK (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'richieste_prenotazione' AND policyname = 'richieste_prenotazione_studio_delete') THEN
    CREATE POLICY richieste_prenotazione_studio_delete ON public.richieste_prenotazione FOR DELETE
      USING (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid);
  END IF;
END $$;

-- ── richieste_prenotazione: WhatsApp requests in the existing list ──────
ALTER TABLE public.richieste_prenotazione
  ADD COLUMN IF NOT EXISTS origine text NOT NULL DEFAULT 'pagina_pubblica',
  ADD COLUMN IF NOT EXISTS paziente_id bigint REFERENCES public.patients(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS tipo_richiesta text NOT NULL DEFAULT 'prenota',
  ADD COLUMN IF NOT EXISTS appuntamento_id bigint REFERENCES public.appointments(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ora_preferita text;

DO $$ BEGIN
  ALTER TABLE public.richieste_prenotazione
    ADD CONSTRAINT richieste_prenotazione_origine_check CHECK (origine IN ('pagina_pubblica', 'whatsapp'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.richieste_prenotazione
    ADD CONSTRAINT richieste_prenotazione_tipo_check CHECK (tipo_richiesta IN ('prenota', 'sposta', 'disdici'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.richieste_prenotazione
    ADD CONSTRAINT richieste_prenotazione_ora_check CHECK (ora_preferita IS NULL OR ora_preferita ~ '^[0-2][0-9]:[0-5][0-9]$');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- The public booking page (anon) must not be able to forge WhatsApp-origin
-- requests or link itself to an existing patient/appointment.
DROP POLICY IF EXISTS richieste_prenotazione_insert_pubblico ON public.richieste_prenotazione;
CREATE POLICY richieste_prenotazione_insert_pubblico ON public.richieste_prenotazione
  FOR INSERT TO anon, authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.studios s WHERE s.id = richieste_prenotazione.studio_id AND s.attivo = true)
    AND origine = 'pagina_pubblica'
    AND paziente_id IS NULL
    AND appuntamento_id IS NULL
    AND tipo_richiesta = 'prenota'
  );

-- ── whatsapp_messages.origine ────────────────────────────────────────────
ALTER TABLE public.whatsapp_messages ADD COLUMN IF NOT EXISTS origine text;
DO $$ BEGIN
  ALTER TABLE public.whatsapp_messages
    ADD CONSTRAINT whatsapp_messages_origine_check CHECK (origine IS NULL OR origine IN ('paziente', 'assistente', 'staff', 'sistema'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── whatsapp_conversazioni ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.whatsapp_conversazioni (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL REFERENCES public.studios(id) ON DELETE CASCADE,
  telefono text NOT NULL,
  paziente_id bigint REFERENCES public.patients(id) ON DELETE SET NULL,
  ai_pausa_fino timestamptz,
  serve_staff boolean NOT NULL DEFAULT false,
  motivo_staff text,
  ultimo_messaggio_il timestamptz NOT NULL DEFAULT now(),
  creata_il timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_conversazioni_studio_telefono_key UNIQUE (studio_id, telefono)
);

ALTER TABLE public.whatsapp_conversazioni ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS whatsapp_conversazioni_select ON public.whatsapp_conversazioni;
CREATE POLICY whatsapp_conversazioni_select ON public.whatsapp_conversazioni
  FOR SELECT TO authenticated
  USING (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid);

-- Staff may only resume the assistant or close a hand-over; column grants
-- below keep every other column server-written.
DROP POLICY IF EXISTS whatsapp_conversazioni_update ON public.whatsapp_conversazioni;
CREATE POLICY whatsapp_conversazioni_update ON public.whatsapp_conversazioni
  FOR UPDATE TO authenticated
  USING (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid)
  WITH CHECK (studio_id = ((auth.jwt() -> 'app_metadata' ->> 'studio_id'))::uuid);

REVOKE ALL ON public.whatsapp_conversazioni FROM anon, authenticated;
GRANT SELECT ON public.whatsapp_conversazioni TO authenticated;
GRANT UPDATE (ai_pausa_fino, serve_staff, motivo_staff) ON public.whatsapp_conversazioni TO authenticated;

-- ── Patient balance for the assistant (service role only) ───────────────
CREATE OR REPLACE FUNCTION public.whatsapp_saldo_paziente_v1(p_studio_id uuid, p_paziente_id bigint)
RETURNS TABLE (piano_id bigint, titolo text, totale_piano numeric, totale_pagato numeric, saldo_piano numeric, scadenza_pagamento date)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
  IF p_studio_id IS NULL OR p_paziente_id IS NULL THEN
    RETURN;
  END IF;
  -- Same tenant scoping the financial views use (see get_saldi_aperti_studio).
  PERFORM set_config('request.financial_studio_override_v1', p_studio_id::text, true);
  IF EXISTS (
    SELECT 1 FROM private.financial_live_data_quality_v1 q
    WHERE q.studio_id = p_studio_id AND q.blocking_metric = 'PLAN_BALANCE'
  ) THEN
    RAISE EXCEPTION 'POL-FIN-006: open balances unavailable due incomplete plan data';
  END IF;

  RETURN QUERY
  SELECT s.piano_id, plan.titolo, s.totale_piano, s.totale_pagato_piano,
         s.totale_piano - s.totale_pagato_piano, plan.scadenza_pagamento
  FROM private.incassi_plan_saldo_v1 s
  JOIN public.plans plan ON plan.id = s.piano_id
  WHERE s.studio_id = p_studio_id
    AND s.paziente_id = p_paziente_id
    AND plan.stato = 'accettato'
    AND s.totale_piano - s.totale_pagato_piano > 0.005
  ORDER BY plan.scadenza_pagamento NULLS LAST, s.piano_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.whatsapp_saldo_paziente_v1(uuid, bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.whatsapp_saldo_paziente_v1(uuid, bigint) TO service_role;

COMMENT ON FUNCTION public.whatsapp_saldo_paziente_v1(uuid, bigint) IS
  'POL-WA-003a: open balances of ONE patient for the WhatsApp assistant. Same source, acceptance gate and data-quality block as get_saldi_aperti_studio; callable only by service_role (the whatsapp-webhook Edge Function).';

COMMIT;
